### ISSUE TITLE
Seems to be breaking with pretender

### ISSUE THREAD

**Issue by rwwagner90** [freshbooks/ember-responsive#112]
When I install ember-responsive and run my tests, all the sudden pretender chokes and throws `Global error: Uncaught Error: Pretender intercepted GET http://localhost:4201/admanager/assets/vendor.js but no handler was defined for this type of request at http://localhost:4201/admanager/assets/vendor.js, line 132009`

Any ideas what the issue could be?

**Comment by k-fish** [comment]
I don't know what's on line 132009 of your vendor.js, so unfortunately not 😄 .

If you have code firing based on responsive behaviour inside your tests, it could be the source of your trouble. Ember-responsive itself shouldn't really be interacting with pretender otherwise.

I'd need the version numbers of both packages and some additional trace information or (ideally) a small repro case to tell you if this is related to ember-responsive.

**Comment by rwwagner90** [comment]
@k-fish it's definitely only an issue after I install ember-responsive. It's odd that it causes pretender to intercept the GET for the actual vendor.js itself. That should be loaded in already. Something might be causing it to load vendor twice. I can definitely throw together a reproduction eventually, but for now we're just defining a passthrough for `/**` in pretender to keep it from doing this.

**Comment by k-fish** [comment]
Ok, I'll investigate this if you provide more information (such as version numbers involved).

**Comment by rwwagner90** [comment]
@k-fish why close the issue? I'm going to make a reproduction, I just haven't had time yet.

**Comment by k-fish** [comment]
Sorry about that, I should have elaborated.

I'm not saying it's not an issue, just that there isn't anything I can do to act on it until more information is provided. As soon as you add a repro, I'll re-open until it's resolved 😄
