### ISSUE TITLE
Use Ember Singularity for DOM event listeners?

### ISSUE THREAD

**Issue by lougreenwood** [freshbooks/ember-responsive#132]
I just came across this add-on (https://github.com/trentmwillis/ember-singularity) - it looks useful.

Is `ember-responsive` using native DOM listeners - if so, it looks like `ember singularity` might be useful...?

**Comment by k-fish** [comment]
Hi Lou, thanks for the recommendation. 

Ember-responsive uses listeners with matchMedia, instead of listeners on DOM nodes. I'm not sure we'd benefit from switching to ember-singularity in any case, ember-responsive isn't a large addon so I'd prefer to keep it's size and dependencies as minimal as possible. If we start using events more heavily, I'll keep it mind going forward though.
