### ISSUE TITLE
Remove auto-injection of media service into everything

### ISSUE THREAD

**Issue by blimmer** [freshbooks/ember-responsive#77]
This is an anti-pattern and can cause strange results. For instance, I just encountered this very strange behavior:

![](https://i.imgur.com/6o98txm.png)

I couldn't figure out what was going on and I tracked it down to [the initializer](https://github.com/freshbooks/ember-responsive/blob/master/addon/initializers/responsive.js) in this project.

Because service injection is so darn easy with `Ember.inject`, I vote that this should be removed.

In fact, other addons like ember-cli-flash have removed this and identified this automatic injection as an anti-pattern ([example](https://github.com/poteto/ember-cli-flash/releases/tag/1.3.12)).

**Comment by blimmer** [comment]
At the very least, this should be configurable. Here are a few options to consider:

## Breaking API Change (preferred)
If we're OK with a breaking API change release, we should make the initializer simply init the service (to [register](https://github.com/freshbooks/ember-responsive/blob/master/addon/media.js#L115) the `breakpoints` options) and do nothing else.

## Non-Breaking
We could introduce a configuration and not release a breaking change. So, by default, the configuration would be to inject into the 4 factories currently defined, but you could change those out (like in 1.x of ember-cli-flash). I would still propose changing this default behavior in a breaking API change release, though, as this is an anti-pattern.

**Comment by k-fish** [comment]
Good call, and thanks for commenting. 

I agree with you that auto-injection should be an anti-pattern. We don't have exactly the same use case as `ember-cli-flash`, because people use `media` in templates frequently, which before didn't require explicitly creating a controller/component, but will with manual injection. It's probably more than a trivial amount of work for people to `inject` and in some cases creating additional files.

So I think non-breaking API would be safest, along with using `deprecate` for the time being to let people know that manual injection is preferred.

**Comment by k-fish** [comment]
@blimmer check the linked PR and see if it works for your situation.

**Comment by k-fish** [comment]
Discussion continued in PR.
