### ISSUE TITLE
Use within addon

### ISSUE THREAD

**Issue by samselikoff** [freshbooks/ember-responsive#84]
Thanks for this awesome addon!

I'm using this addon within an addon, but my `breakpoints.js` isn't registering in the host app. Is there a recommended way to set the breakpoints from within my addon? Perhaps in the initializer? (I fiddled around here but couldn't get anything working.)

**Comment by LBKinson** [comment]
@samselikoff any luck on figuring out a workaround? I'm stuck with the same problem...

**Comment by k-fish** [comment]
@LBKinson he put a PR(https://github.com/freshbooks/ember-responsive/pull/87) that stops ember-responsive from putting the `breakpoint.js` in the application for fallback, instead relying on users doing `ember install` to generate the `breakpoint.js` with blueprints. 

Which will definitely work, each addon has to let the user override the breakpoint file with their own. 

But since this would of course be another breaking change I was hoping for more feedback from addon users.

**Comment by LBKinson** [comment]
thanks for the help!
