### ISSUE TITLE
Chrome browser not resizing

### ISSUE THREAD

**Issue by agoyal-git** [freshbooks/ember-responsive#93]
With chrome version 49.0 i could not get my tests working. I followed the exact steps i.e 
1) Did 'ember install ember-responsive'
2) Modified app/breakpoints.js to the required values as follows:
export default {
  mobile:  '(max-width: 480px)',
  tablet:  '(min-width: 481px) and (max-width: 768px)',
  desktop: '(min-width: 769px) and (max-width: 1366px)'
};
3) Wrote my test as follows -

test('example test', function() {
  setBreakpoint('mobile');
  visit('/');

  return pauseTest();
});

When i look at the browser after the test has paused it still shows up the desktop view and not the mobile view. What could be the possible reasons for it. I don't see any error being shown.

Another question. Does this addon work with phantomJS ?

**Comment by k-fish** [comment]
It should be working properly in acceptance tests, browser or otherwise.

What are you asserting? `media.isMobile` should be returning true and something like `media.isDesktop` should be returning false (that is how the acceptance helper works). The test helper mocks out the responsive calls, it won't actually change the width/height of the testing container.

Does it work normally when not testing?

**Comment by k-fish** [comment]
Reopen if you have further questions.
